### ISSUE TITLE
the collider doesnot work :(

### ISSUE THREAD

**Issue by stickylabdev** [LeMorrow/2D-Procedural-Map-Generation#1]
player keep falling

**Comment by MarcusOtter** [comment]
Hello, thank you for this comment! It seems like Unity changed the way they handle collisions on tilemaps, you are no longer able to have a sprite that is 1x1 pixels and have it generate collision. The latest version has fixed the colliders :)

Note: the project uses Unity version `2017.4`

**Comment by stickylabdev** [comment]
thanks

**Comment by stickylabdev** [comment]
![image](https://user-images.githubusercontent.com/13078369/70577389-c67ca000-1bdd-11ea-8ad7-45824367c056.png)


why the scene is white ?

**Comment by stickylabdev** [comment]
also i want to know how to make the player start from left side ,,,then put finish flag on the right side ?

**Comment by stickylabdev** [comment]
i think i can do it maself ,just need a time to understand

**Comment by stickylabdev** [comment]
i want to know how to makesome thing like fixed map after it has been made ,,,,for example if i use z map , then if i generate again with some code or some thing then iwill get z map again ,, is that posibble?

**Comment by MarcusOtter** [comment]
That functionality is not in this project, no. But it's possible to modify the code to allow it.

**Comment by stickylabdev** [comment]
I'm not sure if I can do it or not ,maybe you can give a little clue ,, maybe i will use playerprefs to save the value but ,,,,,  -_-
